apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: k-ates-crb
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{.Values.project.crb.name}}-view-cr
subjects:
    - kind: ServiceAccount
      name: default
      namespace: default
---
aggregationRule:
    clusterRoleSelectors:
        - matchLabels:
              rbac.authorization.k8s.io/aggregate-to-view: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    annotations:
        rbac.authorization.kubernetes.io/autoupdate: "true"
    labels:
        kubernetes.io/bootstrapping: rbac-defaults
        rbac.authorization.k8s.io/aggregate-to-edit: "true"
    name: {{.Values.project.crb.name}}-view-cr
rules:
    - apiGroups:
          - compose.docker.com
      resources:
          - stacks
          - stacks/scale
          - stacks/log
          - stacks/composeFile
      verbs:
          - get
          - list
          - watch
    - apiGroups:
          - ""
      resources:
          - configmaps
          - endpoints
          - persistentvolumeclaims
          - pods
          - replicationcontrollers
          - replicationcontrollers/scale
          - serviceaccounts
          - services
      verbs:
          - get
          - list
          - watch
    - apiGroups:
          - ""
      resources:
          - bindings
          - events
          - limitranges
          - namespaces/status
          - pods/log
          - pods/status
          - replicationcontrollers/status
          - resourcequotas
          - resourcequotas/status
      verbs:
          - get
          - list
          - watch
    - apiGroups:
          - ""
      resources:
          - namespaces
      verbs:
          - get
          - list
          - watch
    - apiGroups:
          - apps
      resources:
          - controllerrevisions
          - daemonsets
          - deployments
          - deployments/scale
          - replicasets
          - replicasets/scale
          - statefulsets
          - statefulsets/scale
      verbs:
          - get
          - list
          - watch
    - apiGroups:
          - autoscaling
      resources:
          - horizontalpodautoscalers
      verbs:
          - get
          - list
          - watch
    - apiGroups:
          - batch
      resources:
          - cronjobs
          - jobs
      verbs:
          - get
          - list
          - watch
    - apiGroups:
          - extensions
      resources:
          - daemonsets
          - deployments
          - deployments/scale
          - ingresses
          - networkpolicies
          - replicasets
          - replicasets/scale
          - replicationcontrollers/scale
      verbs:
          - get
          - list
          - watch
    - apiGroups:
          - policy
      resources:
          - poddisruptionbudgets
      verbs:
          - get
          - list
          - watch
    - apiGroups:
          - networking.k8s.io
      resources:
          - ingresses
          - networkpolicies
      verbs:
          - get
          - list
          - watch