{{- if or .Values.knativeDeploy .Values.canary.enabled }}
{{- else }}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.project.port }}
    targetPort: {{ .Values.project.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "fullname" . }}
{{- end }}

{{- if .Values.project.ambassador.enabled }}
---
apiVersion: getambassador.io/v1
kind:  Mapping
metadata:
  name:  k-ates
spec:
  prefix: {{ .Values.project.root }}
  service: {{ .Values.service.name }}:{{ .Values.project.port }}

{{- end }}