apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: benbentwo/k-ates
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.USER}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: k-ates
        chartPath: charts/k-ates
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}'
          image.tag: '{{.USER}}'
          project.ambassador.enabled: true
          project.sampleData.enabled: true
- name: devv
  build:
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}:{{.USER}}'
    local: {}
    artifacts:
      - image: benbentwo/k-ates
        context: .
        docker:
          dockerfile: Dockerfile.dev
  deploy:
    helm:
      releases:
        - name: k-ates
          chartPath: charts/k-ates
          setValueTemplates:
            image.repository: '{{.DOCKER_REGISTRY}}/{{.IMAGE_NAME}}'
            image.tag: '{{.USER}}'
            project.ambassador.enabled: true
            project.sampleData.enabled: true
